import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import NavBar from '@/components/NavBar';
import { Toaster } from '@/components/ui/toaster';
import Footer from '@/components/Footer';
import { Providers } from './provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Next e-coomerce Dresscode App',
  description: 'Generated by create next e-coomerce Dresscode app',
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem={true}
            ssr={false}>
            <div className="flex flex-col min-h-screen">
              <NavBar />
              <main className="container flex flex-col justify-stretch flex-grow p-4 my-0 mx-auto">
                {children}
              </main>
              <Footer />
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}
